apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: default
spec:
  selector:
    app: kibana
  ports:
  - protocol: TCP
    port: 5601
    targetPort: http
    nodePort: 30050
  type: "LoadBalancer"
  loadBalancerIP: ""